=== former-sinnr/INSY_XML_SCHEMA/Komplexe/Beispiel_4/euro.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="euro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="team" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="player" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="qualifying">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="group" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="team-play" type="xs:string" maxOccurs="unbounded"/>
                    <xs:element name="news" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== former-sinnr/INSY_XML_SCHEMA/Komplexe/Beispiel_4/euro.xml
<euro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="euro.xsd">
  <team>Schweizer Team</team>
  <team>France</team>
  <player>Gareth Bale</player>
  <player>Jamie Vardi</player>
  <qualifying>
    <group>
      <team-play>FRA</team-play>
      <team-play>SUI</team-play>
      <news>The last match in Group A ended</news>
    </group>
    <group>
      <team-play>RUS</team-play>
      <team-play>GER</team-play>
      <team-play>JAP</team-play>
    </group>
  </qualifying>
</euro>
